### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by JulienItard** [midorikocak/Cakephp-Bootstrappifier#6]
Hi, you should add $('table').addClass('table'); :)

**Comment by midorikocak** [comment]
Can you make a pull request?

2013/4/18 Julien ITARD notifications@github.com

> Hi, you should add $('table').addClass('table'); :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mtkocak/Cakephp-Bootstrappifier/issues/6
> .

## 

Mutlu Tevfik Koçak | Computer Scientist & Engineer
Mobile: +420 776 186 360
V jámě 1371/8 110 00 Praha 1-Nové Město, Česká republika

Blog: http://www.mtkocak.net Personal Website: http://www.mtkocak.com
